apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: node-exporter-systemd
    app.kubernetes.io/part-of: node-exporter-systemd
    prometheus: k8s
    role: alert-rules
  name: alertmanager-systemd-rules
  namespace: openshift-monitoring
spec:
  groups:
  - name: systemd.rules
    rules:
    - alert: HostSystemdServiceCrashed
      expr: node_systemd_unit_state{state="failed"} == 1
      for: 10m
      labels:
        severity: warning
      annotations:
        summary: Host systemd service crashed (instance {{ $labels.instance }})
        description: "systemd service crashed\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
