apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: node-exporter-systemd-tls
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: node-exporter-systemd
    app.kubernetes.io/part-of: node-exporter-systemd
  name: node-exporter-systemd
  namespace: openshift-monitoring
spec:
  clusterIP: None
  clusterIPs:
  - None
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: https
    port: 9101
    protocol: TCP
    targetPort: https
  selector:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: node-exporter-systemd
    app.kubernetes.io/part-of: node-exporter-systemd
  sessionAffinity: None
  type: ClusterIP
